Macy
CS320-Group-1/CS320-Group1 pull request #13
Opened 2024-10-21 14:59 UTC by megraves

MongoDB setup

2024-10-21 16:00 UTC, Jamie11111 approved these changes

2024-10-21 18:09 UTC, DilaOzersen approved these changes

2024-10-21 18:46 UTC, ashleybhandari requested changes
don't add node_modules to the repo

2024-10-22 16:01 UTC, DilaOzersen approved these changes

2024-10-22 16:04 UTC, ashleybhandari approved these changes

2024-10-23 19:06 UTC, megraves commented
Finalized REST API with Node.js, Express, and MongoDB. Server successfully connects to DB. Must still complete routing and model schemas.

2024-10-23 19:07 UTC, merged