Added Regatta Creation
CS320-Group-1/CS320-Group1 pull request #38
Opened 2024-11-17 21:35 UTC by DilaOzersen

- Pages: RegattaCreate, RegattaView (updated), BoatView
- Added BoatList and RegattaResponsiveCard (might be a temp file)
- updated models for Boat and Regatta
- updated regatta-handler and boat-handler

2024-11-17 22:04 UTC, ashleybhandari requested changes

2024-11-17 22:04 UTC, ashleybhandari commented on server/models/subscribers.js
> +    required: null,
false, not null

2024-11-18 00:46 UTC, DilaOzersen commented on flote/src/app/pages/BoatView.tsx
Just to temporarily display the data, was a quick add and completely okay if we delete it later on, just wanted to prove that data was there.

2024-11-18 05:56 UTC, ashleybhandari approved these changes

2024-11-18 11:38 UTC, megraves approved these changes

2024-11-20 17:52 UTC, merged